version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: django_app_dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/apps/*/__pycache__
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.development
      - DEBUG=1
    depends_on:
      - db
      - redis
    networks:
      - app_network_dev

  db:
    image: postgres:15-alpine
    container_name: postgres_db_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - .env.development
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - app_network_dev

  redis:
    image: redis:7-alpine
    container_name: redis_cache_dev
    ports:
      - "6380:6379"
    networks:
      - app_network_dev

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_dev
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app_network_dev

volumes:
  postgres_data_dev:

networks:
  app_network_dev:
    driver: bridge