# Generated by Django 4.2.14 on 2025-01-04 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=250)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('joining_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadModel',
            fields=[
                ('personaldetailmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.personaldetailmodel')),
                ('experience', models.PositiveIntegerField()),
                ('salary', models.PositiveIntegerField()),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.designationmodel')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('app.personaldetailmodel',),
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('personaldetailmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.personaldetailmodel')),
                ('status', models.CharField(choices=[('process', 'process'), ('Pending', 'Pending'), ('success', 'success')], max_length=50)),
                ('manage_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('app.personaldetailmodel',),
        ),
    ]
