# Generated by Django 4.2.14 on 2025-01-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_leadmodel_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldetailmodel',
            name='image',
            field=models.ImageField(default=1, upload_to='profile/'),
            preserve_default=False,
        ),
    ]
